from .resnet import *
from .evonorm import *
from .mobilenetv2 import *
from .vgg import *
from .tinynet import *
from .cganet import *
from .cga import *
from .compresscga import *
from .ngc import *
from .compressngc import *
